version: "3.7"

services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        tty: true
        env_file: bot.env
        volumes:
        - ./logs:/app/bot/logs
volumes:
    logs:
